### ISSUE TITLE
133********该帐号无法登录

### ISSUE THREAD

**Issue by peng1992** [Aierui/web#1]
用bootstrap + jq就整出了一个后台管理系统，而且样式也很好看，塞雷！

**Comment by Aierui** [comment]
已经解决。

**Comment by Aierui** [comment]
已经解决，现在可以重新登录。谢谢你的反馈??

金融先森手机发送

在 2016年11月15日，上午9:07，peng <notifications@github.com<mailto:notifications@github.com>> 写道：


用bootstrap + jq就整出了一个后台管理系统，而且样式也很好看，塞雷！

―
