### ISSUE TITLE
请问我本机配置，左侧菜单不能显示

### ISSUE THREAD

**Issue by jorbin** [Aierui/web#2]
请问我本机配置，左侧菜单不能显示，查看是菜单的cache没有创建，没看到调用菜单缓存的方法啊。
在$_menuList = \app\common\controller\Permission::menuList();这块提示错误，$_menuList为空了

**Comment by jorbin** [comment]
没发现什么地方调用了menu控制器的cache()方法

**Comment by Aierui** [comment]
@jorbin 初次配置需要手动调用 http://yourdomain/admin/menu/cache
因为菜单是缓存在本地，希望能够帮助到你
当然这个问题会在之后完善

**Comment by jorbin** [comment]
thank u. 我试着在登录后调用下这个cache()
